version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Ensure game builds
          command: make game.p8
